version: '3.8'
services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: cs2_db
      POSTGRES_USER: initexample
      POSTGRES_PASSWORD: initexample
    volumes:
      - pgdata:/var/lib/postgresql/data  # persistent db data
    ports:
      - 5431:5432
    networks:
      - initexample

  pythonapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webscraper-app
    depends_on:
      - postgres
    networks:
      - initexample
    volumes:
      - .:/app                          # Mount entire project
      - poetry-cache:/app/.venv         # Keep venv separate
      - /app/__pycache__                # Exclude pycache
    ports:
      - 8000:8000 #host_port:container_port

networks:
  initexample:
    driver: bridge

volumes:
  pgdata:
  poetry-cache: