[project]
name = "webscraper"
version = "0.1.0"
description = ""
authors = [
    {name = "MarwanBit",email = "38559602+MarwanBit@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django (>=5.2.8,<6.0.0)",
    "pytest (>=9.0.0,<10.0.0)"
]

[tool.poetry]
packages = [{include = "webscraper", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
main = 'webscraper.main:main'
