[tool.poetry]
name = "webscraper"
version = "0.1.0"
description = ""
authors = ["MarwanBit <38559602+MarwanBit@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "webscraper", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.12"
django = ">=5.2.8,<6.0.0"
numpy = "^2.3.5"

[tool.poetry.group.dev.dependencies]
pytest = ">=9.0.0,<10.0.0"
ruff = ">=0.14.5,<0.15.0"

[tool.poetry.scripts]
main = "webscraper.main:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"